name: Deploy Worker

on:
  repository_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"

      - name: Install Wrangler
        run: npm install wrangler@latest

      - name: Build
        run: npx wrangler build

      - name: Add Header
        run: |
          cp ${{ github.workspace }}/dist/worker.js ${{ github.workspace }}/dist/worker-original.js
          echo -e "/*!\n  * v2ray Subscription Worker (${{ github.sha }})\n  * Copyright 2024 Vahid Farid (https://twitter.com/vahidfarid)\n  * Licensed under GPLv3 (https://github.com/vfarid/v2ray-worker/blob/main/Licence.md)\n  */\n\n$(cat ${{ github.workspace }}/dist/worker.js)" > ${{ github.workspace }}/dist/worker.js

      - name: Deploy to Cloudflare
        env:
          KV_NAME: ${{ secrets.KV_NAME }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          sed -i "s/__KV_NAME__/$KV_NAME/g" wrangler.toml
          npx wrangler deploy --api-token $CF_API_TOKEN --account-id $CF_ACCOUNT_ID


